ALTER TABLE FACT1_COVID_COUNT
ADD CONSTRAINT FK_FACT1_COVID_COUNT_DIM_PHU
FOREIGN KEY (PHU_SK)
REFERENCES DIM_PHU(PHU_SK)
GO

ALTER TABLE FACT1_COVID_COUNT
ADD CONSTRAINT FK_FACT1_COVID_COUNT_DIM_YEAR
FOREIGN KEY (Year_SK)
REFERENCES DIM_YEAR(Year_SK)
GO
---------------------
ALTER TABLE FACT2_SEVERITY
ADD CONSTRAINT FK_FACT2_SEVERITY_DIM_SEVERITY
FOREIGN KEY (SEVERITY_SK)
REFERENCES DIM_SEVERITY(SEVERITY_SK)
GO

ALTER TABLE FACT2_SEVERITY
ADD CONSTRAINT FK_FACT2_SEVERITY_PHU_SK
FOREIGN KEY (PHU_SK)
REFERENCES DIM_PHU(PHU_SK)
GO

ALTER TABLE FACT2_SEVERITY
ADD CONSTRAINT FK_FACT2_SEVERITY_DIM_QUATER
FOREIGN KEY (QUATER_SK)
REFERENCES DIM_QUATER(QUATER_SK)
GO
----------------
ALTER TABLE FACT3_CASES
ADD CONSTRAINT FK_FACT3_CASES_DIM_GENDER
FOREIGN KEY (Gender_SK)
REFERENCES DIM_GENDER(Gender_SK)
GO

ALTER TABLE FACT3_CASES
ADD CONSTRAINT FK_FACT3_CASES_DIM_AGE_GROUP
FOREIGN KEY (AgeGroup_SK)
REFERENCES DIM_AGE_GROUP(AgeGroup_SK)
GO

ALTER TABLE FACT3_CASES
ADD CONSTRAINT FK_FACT3_CASES_DIM_YEAR
FOREIGN KEY (Year_SK)
REFERENCES DIM_YEAR(Year_SK)
GO
---------------------
ALTER TABLE [dbo].[FACT_A]
ADD CONSTRAINT FK_FACT4_5A_CASES_DIM_SEVERITY
FOREIGN KEY (SEVERITY_SK)
REFERENCES DIM_SEVERITY(SEVERITY_SK)
GO

ALTER TABLE [dbo].[FACT_A]
ADD CONSTRAINT FK_FACT4_5A_CASES_DIM_DATE
FOREIGN KEY (DATE_SK)
REFERENCES DIM_DATE(DATE_SK)
GO
------------------
ALTER TABLE FACT5B_VACCINES
ADD CONSTRAINT FK_FACT4_5A_CASES_DIM_YEAR
FOREIGN KEY (Year_SK)
REFERENCES DIM_YEAR(Year_SK)
GO
--------------------------
ALTER TABLE FACT6_CASES
ADD CONSTRAINT FK_FACT6_CASES_DIM_PHU_GROUP
FOREIGN KEY (PHU_GROUP_SK)
REFERENCES DIM_PHU_GROUP(PHU_GROUP_SK)
GO

ALTER TABLE FACT6_CASES
ADD CONSTRAINT FK_FACT6_CASES_DIM_SEVERITY
FOREIGN KEY (SEVERITY_SK)
REFERENCES DIM_SEVERITY(SEVERITY_SK)
GO

ALTER TABLE FACT6_CASES
ADD CONSTRAINT FK_FACT6_CASES_DIM_OUT_BREAK_GROUP
FOREIGN KEY (OUT_BREAK_GROUP_SK)
REFERENCES DIM_OUT_BREAK_GROUP(OUT_BREAK_GROUP_SK)
GO

ALTER TABLE FACT6_CASES
ADD CONSTRAINT FK_FACT6_CASES_DIM_YEAR
FOREIGN KEY (YEAR_SK)
REFERENCES DIM_YEAR(YEAR_SK)
GO
--------------
ALTER TABLE DIM_PHU
ADD CONSTRAINT FK_DIM_PHU_DIM_CITY
FOREIGN KEY (City_ID)
REFERENCES DIM_CITY(City_SK)
GO

ALTER TABLE DIM_CITY
ADD CONSTRAINT FK_DIM_CITY_DIM_PHU_GROUP
FOREIGN KEY (PHU_Group_ID)
REFERENCES DIM_PHU_GROUP(PHU_Group_SK)
GO
----------------------------
ALTER TABLE DIM_DATE
ADD CONSTRAINT FK_DIM_DATE_DIM_MONTH
FOREIGN KEY (MONTH_SK)
REFERENCES DIM_MONTH(MONTH_SK)
GO

ALTER TABLE DIM_MONTH
ADD CONSTRAINT FK_DIM_MONTH_DIM_QUATER
FOREIGN KEY (Quater_SK)
REFERENCES DIM_QUATER(Quater_SK)
GO

ALTER TABLE DIM_QUATER
ADD CONSTRAINT FK_DIM_QUATER_DIM_YEAR
FOREIGN KEY (Year_SK)
REFERENCES DIM_YEAR(Year_SK)
GO


ALTER TABLE [dbo].[FACT5A]
ADD CONSTRAINT FK_FACT5A_DIM_PHU
FOREIGN KEY ([PHU_SK])
REFERENCES DIM_PHU([PHU_SK])
GO

ALTER TABLE [dbo].[FACT5A]
ADD CONSTRAINT FK_FACT5A_DIM_SEVERITY
FOREIGN KEY ([SEVERITY_SK])
REFERENCES DIM_SEVERITY([SEVERITY_SK])
GO
------------------------------------------------------------------------
ALTER TABLE [dbo].[FACT6_NEW]
ADD CONSTRAINT FK_DIM_YEAR
FOREIGN KEY (Year_SK)
REFERENCES DIM_YEAR(Year_SK)
GO
ALTER TABLE [dbo].[FACT6_NEW]
ADD CONSTRAINT FK_SEVERITY_SK
FOREIGN KEY (SEVERITY_SK)
REFERENCES DIM_SEVERITY(SEVERITY_SK)
GO
ALTER TABLE [dbo].[FACT6_NEW]
ADD CONSTRAINT FK_PHU_GROUP_SK
FOREIGN KEY (PHU_GROUP_SK)
REFERENCES DIM_PHU_GROUP(PHU_GROUP_SK)
GO
ALTER TABLE [dbo].[FACT6_NEW]
ADD CONSTRAINT FK_ACIQUISITION_SK
FOREIGN KEY ([ACIQUISITION_SK])
REFERENCES [dbo].[DIM_CASE_ACQUISITION](ACQUISITION_SK)
GO